[package]
name = "tracks"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.5"
quote = "1.0.2"
proc-macro2 = "1.0.2"
regex = "1.5.5"
semver = "1.0.6"
